// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAuth(arg1, arg2) {
  return window['go']['auth']['AuthService']['CreateAuth'](arg1, arg2);
}

export function CreateAuthInTransaction(arg1, arg2, arg3) {
  return window['go']['auth']['AuthService']['CreateAuthInTransaction'](arg1, arg2, arg3);
}

export function CreateUserWithAuth(arg1, arg2, arg3, arg4) {
  return window['go']['auth']['AuthService']['CreateUserWithAuth'](arg1, arg2, arg3, arg4);
}

export function DeleteAuth(arg1, arg2) {
  return window['go']['auth']['AuthService']['DeleteAuth'](arg1, arg2);
}

export function ForgotPassword(arg1, arg2) {
  return window['go']['auth']['AuthService']['ForgotPassword'](arg1, arg2);
}

export function GetAllAuth(arg1) {
  return window['go']['auth']['AuthService']['GetAllAuth'](arg1);
}

export function GetAuthByCredentials(arg1, arg2, arg3) {
  return window['go']['auth']['AuthService']['GetAuthByCredentials'](arg1, arg2, arg3);
}

export function GetAuthByID(arg1, arg2) {
  return window['go']['auth']['AuthService']['GetAuthByID'](arg1, arg2);
}

export function GetAuthByUserID(arg1, arg2) {
  return window['go']['auth']['AuthService']['GetAuthByUserID'](arg1, arg2);
}

export function Login(arg1, arg2) {
  return window['go']['auth']['AuthService']['Login'](arg1, arg2);
}

export function UpdateAuth(arg1, arg2) {
  return window['go']['auth']['AuthService']['UpdateAuth'](arg1, arg2);
}

export function UpdatePasswordByNickname(arg1, arg2) {
  return window['go']['auth']['AuthService']['UpdatePasswordByNickname'](arg1, arg2);
}

export function ValidateToken(arg1) {
  return window['go']['auth']['AuthService']['ValidateToken'](arg1);
}
