// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {auth} from '../models';
import {pgx} from '../models';

export function CreateAuth(arg1:context.Context,arg2:auth.CreateAuthRequest):Promise<auth.Auth>;

export function CreateAuthInTransaction(arg1:context.Context,arg2:pgx.Tx,arg3:auth.CreateAuthRequest):Promise<auth.Auth>;

export function CreateUserWithAuth(arg1:context.Context,arg2:auth.CreateAuthRequest,arg3:string,arg4:string):Promise<auth.Auth>;

export function DeleteAuth(arg1:context.Context,arg2:string):Promise<void>;

export function ForgotPassword(arg1:context.Context,arg2:auth.ForgotPasswordRequest):Promise<void>;

export function GetAllAuth(arg1:context.Context):Promise<Array<auth.Auth>>;

export function GetAuthByID(arg1:context.Context,arg2:string):Promise<auth.Auth>;

export function GetAuthByNickname(arg1:context.Context,arg2:string):Promise<auth.Auth>;

export function GetAuthByUserID(arg1:context.Context,arg2:string):Promise<auth.Auth>;

export function Login(arg1:context.Context,arg2:auth.LoginRequest):Promise<auth.LoginResponse>;

export function UpdateAuth(arg1:context.Context,arg2:auth.UpdateAuthRequest):Promise<auth.Auth>;

export function UpdatePasswordByNickname(arg1:context.Context,arg2:auth.UpdatePasswordRequest):Promise<void>;

export function ValidateToken(arg1:string):Promise<auth.Claims>;
