// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBybit(arg1) {
  return window['go']['bybit']['BybitService']['CreateBybit'](arg1);
}

export function GetBybitByUserId(arg1) {
  return window['go']['bybit']['BybitService']['GetBybitByUserId'](arg1);
}

export function UpsertBybit(arg1, arg2, arg3) {
  return window['go']['bybit']['BybitService']['UpsertBybit'](arg1, arg2, arg3);
}
