// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {bybit} from '../models';

export function CreateBybit(arg1:bybit.Bybit):Promise<string>;

export function GetBybitByUserId(arg1:string):Promise<bybit.Bybit>;

export function UpsertBybit(arg1:string,arg2:string,arg3:string):Promise<void>;
