// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {user} from '../models';

export function CreateOrUpdate(arg1:user.User):Promise<string>;

export function GetUser(arg1:string):Promise<user.User>;
