// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {user} from '../models';
import {context} from '../models';
import {pgx} from '../models';

export function CreateOrUpdate(arg1:user.User):Promise<string>;

export function CreateUserInTransaction(arg1:context.Context,arg2:pgx.Tx,arg3:user.User):Promise<string>;

export function GetUser(arg1:string):Promise<user.User>;
