// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateOrUpdate(arg1) {
  return window['go']['user']['UserService']['CreateOrUpdate'](arg1);
}
