// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateUserInTransaction(arg1, arg2, arg3) {
  return window['go']['user']['UserService']['CreateUserInTransaction'](arg1, arg2, arg3);
}

export function GetUser(arg1) {
  return window['go']['user']['UserService']['GetUser'](arg1);
}

export function UpdateUser(arg1) {
  return window['go']['user']['UserService']['UpdateUser'](arg1);
}
