// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAuth(arg1) {
  return window['go']['main']['App']['CreateAuth'](arg1);
}

export function CreateUserWithAuth(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateUserWithAuth'](arg1, arg2, arg3);
}

export function DeleteAuth(arg1) {
  return window['go']['main']['App']['DeleteAuth'](arg1);
}

export function ForgotPassword(arg1) {
  return window['go']['main']['App']['ForgotPassword'](arg1);
}

export function GetAllAuth() {
  return window['go']['main']['App']['GetAllAuth']();
}

export function GetAuthByID(arg1) {
  return window['go']['main']['App']['GetAuthByID'](arg1);
}

export function GetAuthByUserID(arg1) {
  return window['go']['main']['App']['GetAuthByUserID'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function UpdateAuth(arg1) {
  return window['go']['main']['App']['UpdateAuth'](arg1);
}

export function UpdatePasswordByNickname(arg1) {
  return window['go']['main']['App']['UpdatePasswordByNickname'](arg1);
}

export function ValidateToken(arg1) {
  return window['go']['main']['App']['ValidateToken'](arg1);
}
