// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {auth} from '../models';

export function CreateAuth(arg1:auth.CreateAuthRequest):Promise<auth.Auth>;

export function CreateUserWithAuth(arg1:auth.CreateAuthRequest,arg2:string,arg3:string):Promise<auth.Auth>;

export function DeleteAuth(arg1:string):Promise<void>;

export function ForgotPassword(arg1:auth.ForgotPasswordRequest):Promise<void>;

export function GetAllAuth():Promise<Array<auth.Auth>>;

export function GetAuthByID(arg1:string):Promise<auth.Auth>;

export function GetAuthByUserID(arg1:string):Promise<auth.Auth>;

export function Greet(arg1:string):Promise<string>;

export function Login(arg1:auth.LoginRequest):Promise<auth.LoginResponse>;

export function UpdateAuth(arg1:auth.UpdateAuthRequest):Promise<auth.Auth>;

export function UpdatePasswordByNickname(arg1:auth.UpdatePasswordRequest):Promise<void>;

export function ValidateToken(arg1:string):Promise<auth.Claims>;
